# CMake generated Testfile for 
# Source directory: /mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp
# Build directory: /mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(spz_gatekeeper_self_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/spz_gatekeeper" "--self-test")
set_tests_properties(spz_gatekeeper_self_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;165;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(spz_gatekeeper_unit_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/spz_gatekeeper_test")
set_tests_properties(spz_gatekeeper_unit_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;169;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(extension_validator_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/extension_validator_test")
set_tests_properties(extension_validator_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;171;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(adobe_extension_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/adobe_extension_test")
set_tests_properties(adobe_extension_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;172;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(validator_registry_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/validator_registry_test")
set_tests_properties(validator_registry_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;173;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(extension_spec_registry_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/extension_spec_registry_test")
set_tests_properties(extension_spec_registry_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;174;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(registry_cli_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/registry_cli_test")
set_tests_properties(registry_cli_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;175;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(gen_fixture_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/gen_fixture_test")
set_tests_properties(gen_fixture_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;176;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(compat_check_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/compat_check_test")
set_tests_properties(compat_check_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;177;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(audit_summary_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/audit_summary_test")
set_tests_properties(audit_summary_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;178;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(tlv_multi_record_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/tlv_multi_record_test")
set_tests_properties(tlv_multi_record_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;179;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(extension_integration_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/extension_integration_test")
set_tests_properties(extension_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;180;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
add_test(sh_quantization_test "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/build-wsl/sh_quantization_test")
set_tests_properties(sh_quantization_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;162;add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;181;spz_gatekeeper_add_test;/mnt/c/Users/HP/Downloads/HunYuan3D_test_cases/spz_gatekeeper_project/cpp/CMakeLists.txt;0;")
